version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest

jobs:
  config:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

  gh-pages:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - "06:21:07:ff:96:79:43:fc:a5:44:e9:1a:d9:3e:bb:6d"
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run build
          command: NODE_ENV=production yarn build --public-url /$CIRCLE_PROJECT_REPONAME/ --no-source-maps
      - run:
          name: Copy build
          command: |
            git rm package.json
            git rm yarn.lock
            git rm -rf .circleci
            git rm -rf src
            cp -a dist .
            rm -rf dist
      - run:
          name: Deploy
          command: |
            git add -A
            git commit --allow-empty -m "Deploy to GitHub pages [ci skip]"
            git push --force --quiet origin gh-pages


workflows:
  version: 2
  deploy:
    jobs:
      - config:
          filters:
            branches:
              only: /master/
      - gh-pages:
          requires:
            - config
          filters:
              branches:
                only: /master/
